name: Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  helloworld:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Imprimir en consola
        run: echo "Hello World, GITHUB ACTIONS"

  test:
    needs: helloworld
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test FastAPI imports
        env:
          MONGODB_URI: ${{ secrets.URI }} # tu código usa MONGODB_URI, el secreto se llama URI
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_CREDENTIAL_BASE64: ${{ secrets.FIREBASE_CREDENTIAL_BASE64 }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          python -c "from main import app; print('FASTAPI app imported successfully')"
